# -*- coding: utf-8 -*-
"""commerce_dap_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHUYcU1_8NSB5MsBUhUqtKlNdixnyA0P

# **Quick Commerce Data Analysis**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import plotly.express as px

df = pd.read_csv("quick_commerce_data_raw.csv")

#dataset structure

df.info()

# summary statistics

df.describe()

#check missing values

df.isna().sum()

#to show the records which contains any or all null values

df[df.isna().any(axis=1)]

#to show the records which contains all null values
df[df.isna().all(axis=1)]

"""# **Data Cleaning**

**Remove Rows having null values**
"""

#drop these rows that have missing values in city column

df = df.dropna(subset= ['City'])

x=df['Items_Count'].mode()

# fill items_count column null values

df['Items_Count'] = df['Items_Count'].fillna(x[0])

df.isna().sum()

"""**fill null values with group-wise mean/median**"""

df["Customer_Rating"]=df.groupby("Company")["Customer_Rating"].transform(lambda x:x.fillna(x.mean()))

df["Delivery_Partner_Rating"]=df.groupby("Delivery_Time_Min")["Delivery_Partner_Rating"].transform(lambda y:y.fillna(y.mean()))

df.isna().sum()

df["Delivery_Partner_Rating"]=df["Delivery_Partner_Rating"].fillna(df["Delivery_Partner_Rating"].mean())

df.isna().sum()

df.info()

"""# **Remove Outliers**

**check outliers**
"""

plt.figure(figsize=(15,6))
df.boxplot()

plt.figure(figsize=(15,6))
df.drop(columns=["Order_ID"]).boxplot()

df["Order_Value"]=df["Order_Value"].clip(upper=2500)

df[df["Order_Value"]<=2500]

plt.figure(figsize=(15,6))
df.drop(columns=["Order_ID"]).boxplot(vert=False, showmeans=True)

"""**Change column data type**"""

df['Order_ID']=df['Order_ID'].astype(str)

#round - off float values

df['Order_Value']= np.round(df['Order_Value'])
df['Delivery_Time_Min']= np.round(df['Delivery_Time_Min'])
df['Customer_Rating']= np.round(df['Customer_Rating'])
df['Delivery_Partner_Rating']= np.round(df['Delivery_Partner_Rating'])
df['Distance_Km']= np.round(df['Distance_Km'],1) #i want 1 decimal value so 1 parameter was kept

"""**Save cleaned and modifies dataset**"""

import os

new_path = r"quick_commerce_data_modified_cleaned.csv"

df.to_csv(new_path, index=False)

print("Saved:", os.path.exists(new_path))

print(os.path.abspath(new_path))

"""**Load Cleaned & Modified dataset**"""

df = pd.read_csv("quick_commerce_data_modified_cleaned.csv")

df

"""# **>> Business Questions <<**

**which quick commerce platform has the highest total revenue**
"""

Company_Revenue = df.groupby("Company")["Order_Value"].sum()

Company_Revenue

#sort grouped data

Company_Revenue.sort_values()

#Bar Chart And Line Chart

plt.figure(figsize=(8,5))

#find max and min revenue
max_revenue = Company_Revenue.max()
min_revenue = Company_Revenue.min()

#assign colors based on value
colors = ['green' if val == max_revenue else
          'red' if val== min_revenue else
          'olive'
          for val in Company_Revenue
          ]


#draw bar and line chart at once
Company_Revenue.plot(kind='bar', color=colors ,width=0.3)
Company_Revenue.plot(kind='line',color='black',marker="*")

plt.title("Total Revenue by commerce platform")
plt.xlabel("Quick Commerce Platforms",fontsize=12)
plt.ylabel("Total Revenue",fontsize=12)
plt.xticks(rotation=45,ha="right")

ax=plt.gca() #gca-get current axis

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()

plt.show()

"""**which platform has the highest average order value(AOV)**"""

AOV = df.groupby('Company')['Order_Value'].mean().sort_values()

#stem chart

plt.figure(figsize=(10,4))

plt.stem(AOV.index,AOV.values)

plt.xlabel("Quick Commerce Platforms",fontsize=12)
plt.ylabel("Average Order Value",fontsize=12)
plt.title("Average Order Value by Quick Commerce Platform")
plt.xticks(rotation=30,ha="right")

ax=plt.gca() #gca-get current axis

ax.spines['top'].set_linewidth(4)
ax.spines['right'].set_linewidth(4)
ax.spines['left'].set_linewidth(4)
ax.spines['bottom'].set_linewidth(4)

plt.tight_layout()

plt.show()

"""**How does customer rating vary across platform**"""

df.groupby("Company")['Customer_Rating'].mean().sort_values()

df.boxplot(column='Customer_Rating',by='Company', showmeans=True)

plt.xlabel("Quick Commerce Platforms",fontsize=12)
plt.ylabel("Customer Rating",fontsize=12)
plt.title("Customer Rating Distribution Across Platforms")
plt.xticks(rotation=30,ha="right")
plt.suptitle("") #remove default pandas title

plt.tight_layout()
plt.show()

grouped_rating=df.groupby(["Company",'Customer_Rating']).size().unstack(fill_value=0)

#unstack reshape the ouput in a table format

grouped_rating.plot(kind='bar',stacked=True)

plt.xlabel("Quick Commerce Platforms",fontsize=12)
plt.ylabel("Customer Rating",fontsize=12)
plt.title("Customer Rating Distribution Across Platforms")
plt.xticks(rotation=30,ha="right")
plt.legend(title="Customer Rating",bbox_to_anchor=(1,0.7),loc='upper left')

plt.tight_layout()
plt.show()

"""**Does delivery time affects the delivery partner ratings**"""

df.head()

df["Delivery_Time_Min"].mean()

df["Delivery_Partner_Rating"].mean()

s=df.groupby("Delivery_Time_Min")['Delivery_Partner_Rating'].mean()

df["Delivery_Time_Min"].corr(df["Delivery_Partner_Rating"])

# line chart
s.plot(marker="*")

plt.xlabel("Deliver Time in Minutes")
plt.ylabel("Average Delivery Partner Rating")
plt.title("Delivery Time vs Delivery Partner Rating")
plt.grid(True)

plt.tight_layout()
plt.show()

#cut function is to convert numerical data to categorical data

df["Delivery_Time_Bucket"]=pd.cut(df["Delivery_Time_Min"],bins=(0,10,20,30,40,50),
       labels=("very fast delivery","fast delivery","normal delivery","slow delivery","very slow delivery"))

bucket_average=df.groupby("Delivery_Time_Bucket")['Delivery_Partner_Rating'].mean()
bucket_average

plt.figure(figsize=(8,5))

bucket_average.plot(marker="*",color="purple")

plt.xlabel("Delivery Time Bucket")
plt.ylabel("Average Delivery Partner Rating")
plt.title("Impact of delivery time on delivery partner rating")
plt.grid(True)

plt.tight_layout()
plt.show()

"""**what is the most popular product category on swiggy instamart , for the people of age between 30-40 in mumbai**"""

df_pc=df[(df["Company"]=="Swiggy Instamart") &
((df["Customer_Age"]>=30) & (df["Customer_Age"]<=40)) &
(df["City"]=="Mumbai")]

df_pc['Product_Category'].value_counts()

"""**which cities should these company expand based on performance**"""

city_performance = df.groupby(['Company','City']).agg(
    Total_Orders=('Order_ID','count'),
    Total_Revenue=('Order_Value','sum'),
    Average_Rating=('Customer_Rating','mean'),
    Average_Delivery_Time=('Delivery_Time_Min','mean')
)

best_cities = city_performance[
    (city_performance['Total_Orders'] >= city_performance['Total_Orders'].median()) &
    (city_performance['Average_Rating'] >= 3.5) &
    (city_performance['Average_Delivery_Time'] <= 15)
]

best_cities

sns.barplot(data=best_cities,x="City",y="Total_Revenue",hue="Company",edgecolor="yellow")
plt.show()

"""**Are discounts increasing order values or reducing revenue**"""

# count the number of orders with discount and without

df['Discount_Applied'].value_counts()

# group data - calculate average order of values

dis_order_value = df.groupby('Discount_Applied')['Order_Value'].mean()

# group data - calculate sum of items count
dis_items_count = df.groupby('Discount_Applied')['Items_Count'].sum()

x= df['Discount_Applied'].unique()

plt.figure(figsize=(12,8))
colors = sns.color_palette("coolwarm",len(x))

plt.subplot(2,2,1)
dis_order_value.plot(kind="bar",width=0.3,color=colors)
plt.title("Average Order Value")

plt.subplot(2,2,2)
dis_items_count.plot(kind="bar",width=0.3,color=colors)
plt.title("Average item count")

plt.show()

"""**which company has the best opeartional efficiency(deliver time vs order volume)**"""

# group data and apply aggreagate functions
company_efficiency = df.groupby('Company').agg(
    Total_Orders=('Order_ID','count'),
    Average_Delivery_Time=('Delivery_Time_Min','mean')
).reset_index()
company_efficiency

# normalize values for comparison

from sklearn.preprocessing import MinMaxScaler

#scaling both columns to the same range (0 to 1) so that they can be fairely compared and combied

scaler = MinMaxScaler() #create a scaling object
company_efficiency[['Total_Orders_Scaled','Average_Delivery_Time_Scaled']] = scaler.fit_transform(company_efficiency[['Total_Orders','Average_Delivery_Time']])

company_efficiency

#efficiency score (higher orders, lower time)

company_efficiency['Efficiency_Score']= company_efficiency['Total_Orders_Scaled'] - company_efficiency['Average_Delivery_Time_Scaled']

company_efficiency

#sort by best efficiency

eff = company_efficiency.sort_values(by='Efficiency_Score' , ascending=False)
eff

plt.bar(eff['Company'] , eff['Efficiency_Score'])

plt.xlabel('Company')
plt.ylabel('Efficinecy Score')
plt.title("Operational Efficiency Score by company")

plt.xticks(rotation=30, ha='right')

plt.grid(True)
plt.tight_layout()
plt.show()

#use plotly library - scatter bubble plot

import plotly.express as px

#create positive bubble size
min_eff = eff['Efficiency_Score'].min()
eff['Bubble_Size'] = eff['Efficiency_Score']- min_eff + 0.1

#plot
fig = px.scatter(eff,x='Total_Orders',y='Average_Delivery_Time',size='Bubble_Size',color='Company',
text='Company',title ="Operational Efficiency of Quick Commerce Platforms",hover_data={'Total_Orders':True , "Average_Delivery_Time": ':.2f' ,
                                                                                       "Efficiency_Score" : ':.3f'},
                 size_max=40)

#make labels cleaner
fig.update_traces(textposition='middle center')

#improve chart
fig.update_layout(
    xaxis_title="Total Orders(higher is better)",
    yaxis_title="Average Delivery Time(lower is better)",
    title_x=0.5,
    template = "plotly_dark",
    height=600)

#reverse y-axis so best performers appear higher
fig.update_yaxes(autorange='reversed')

fig.show()

df.head(
)

"""# **Mini Dashboard**"""

import matplotlib.pyplot as plt
import seaborn as sns

#create dashboard layout

fig = plt.figure(figsize=(12,12))

sns.set_style("whitegrid")

#KPI calculation

total_orders = df['Order_ID'].count()
total_revenue = df['Order_Value'].sum()
average_delivery_time = df['Delivery_Time_Min'].mean()
average_rating = df['Customer_Rating'].mean()

#KPI cards

plt.subplot2grid((3,4),(0,0))
plt.axis('off')
plt.text(0.5,0.6,f"{total_orders:,}",fontsize=25, ha='center')
plt.text(0.5,0.4 , "Total Orders" , fontsize=15, ha='center',fontstyle='italic',fontweight='bold')


plt.subplot2grid((3,4),(0,1))
plt.axis('off')
plt.text(0.5,0.6,f"₹{total_revenue:,}",fontsize=25, ha='center')
plt.text(0.5,0.4 , "Total Revenue" , fontsize=15, ha='center',fontstyle='italic',fontweight='bold')

plt.subplot2grid((3,4),(0,2))
plt.axis('off')
plt.text(0.5,0.6,f"{average_delivery_time:.2f}",fontsize=25, ha='center')
plt.text(0.5,0.4 , "Average Delivery Time" , fontsize=15, ha='center',fontstyle='italic',fontweight='bold')

plt.subplot2grid((3,4),(0,3))
plt.axis('off')
plt.text(0.5,0.6,f"{average_rating:.2f}",fontsize=25, ha='center')
plt.text(0.5,0.4 , "Average Customer Rating" , fontsize=15, ha='center',fontstyle='italic',fontweight='bold')


#company level metrices

company_metrices = df.groupby('Company').agg(
    Orders=('Order_ID','count'),
    Revenue=('Order_Value','sum'),
    Avg_Delivery_Time=('Delivery_Time_Min','mean'),
    Avg_Rating =('Customer_Rating','mean')).reset_index()

#charts Section

#orders by company
plt.subplot2grid((3,2),(1,0))
sns.barplot(data=company_metrices,x='Company',y='Orders', palette='viridis')
plt.title("Orders  by company", fontsize=20)
plt.xticks(rotation=30,ha='right')

#revenue by company
plt.subplot2grid((3,2),(1,1))
sns.barplot(data=company_metrices,x='Company',y='Revenue', palette='plasma')
plt.title("Revenue  by company", fontsize=20)
plt.xticks(rotation=30,ha='right')

#average delivery time by company
plt.subplot2grid((3,2),(2,0))
sns.barplot(data=company_metrices,x='Company',y='Avg_Delivery_Time', palette='magma')
plt.title("Average delivery time by company", fontsize=20)
plt.xticks(rotation=30,ha='right')

#average rating by company
plt.subplot2grid((3,2),(2,1))
sns.barplot(data=company_metrices,x='Company',y='Avg_Rating', palette='cividis')
plt.title("Average rating by company", fontsize=20)
plt.xticks(rotation=30,ha='right')

#dashboard title

#plt.rcParams['font.family'] = 'DejaVu Sans'
plt.suptitle("Quick Commerce Dashboard",fontsize=30,color = 'navy')

plt.tight_layout()
plt.show()